# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [3]:
arr = np.arange(2, 50, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
first_list = []
second_list = []

for a in range(0,5):
    number = int(input("please enter a number for first list: "))
    first_list.append(number)

for a in range(0,5):
    number = int(input("please enter a number for second list: "))
    second_list.append(number)

please enter a number for first list: 2
please enter a number for first list: 3
please enter a number for first list: 4
please enter a number for first list: 66
please enter a number for first list: 7
please enter a number for second list: 8
please enter a number for second list: 9
please enter a number for second list: 10
please enter a number for second list: 33
please enter a number for second list: 22


In [6]:
first_ = np.array(first_list)
second_ = np.array(second_list)
first_

array([ 2,  3,  4, 66,  7])

In [7]:
second_

array([ 8,  9, 10, 33, 22])

In [12]:
first_second = np.concatenate((first_, second_), axis=0)

In [13]:
print(first_second)

[ 2  3  4 66  7  8  9 10 33 22]


In [14]:
first_second_sorted = np.sort(first_second)   

In [15]:
print(first_second_sorted)

[ 2  3  4  7  8  9 10 22 33 66]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [16]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape) 
print("Size of array: ", arr.size)

No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [19]:
x = np.array([1, 2 , 5 , 6])
x.shape

(4,)

In [20]:
y = np.expand_dims(x, axis=0)

In [21]:
y

array([[1, 2, 5, 6]])

In [22]:
y.shape

(1, 4)

In [23]:
arr_2d = np.reshape(y, (2, 2))

In [24]:
arr_2d

array([[1, 2],
       [5, 6]])

# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [25]:
arr1 = np.array([[ 1, 2, 3], [ 6, 7, 8]] ) 

arr2 = np.array([[ 4, 5, 10], [ 20, 15, 26]] ) 

In [26]:
out_V = np.vstack((arr1, arr2)) 
out_V

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 4,  5, 10],
       [20, 15, 26]])

In [27]:
out_H = np.hstack((arr1, arr2)) 
out_H

array([[ 1,  2,  3,  4,  5, 10],
       [ 6,  7,  8, 20, 15, 26]])

# Questions 6:
How to get unique items and counts of unique items?

In [30]:
arr = np.array([[1, 1, 2, 3]])

In [31]:
np.unique(arr)

array([1, 2, 3])

In [32]:
arr_2 = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(arr_2, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
